spring:
  application:
    name: quadrafacil

  datasource:
    url: jdbc:postgresql://ep-steep-truth-ac7ap21k-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_pB8QwO1YgkxG
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true